export const DRAW_CELLS = "DRAW_CELLS";
export const CHANGE_VALUE = "CHANGE_VALUE";
export const CHANGE_ACTIVE_ELEMENT = "CHANGE_ACTIVE_ELEMENT";
export const SWITCH_CURRENCY_MODE = "SWITCH_CURRENCY_MODE";
export const SWITCH_NUMBER_MODE = "SWITCH_NUMBER_MODE";
export const SWITCH_CURRENCY_TYPE = "SWITCH_CURRENCY_TYPE";
